rmwork.py: run do_rm_work more aggressively
Often when bitbake runs out of disk space under TravisCI, the
"downloads" directory (and presumably also the temp directory)
contains files from completed recipes which would have been removed if
their do_rm_work tasks had been run.

do_rm_work seems to run reliably for virtual native recipes directly after
building the recipe, but not for target recipes. Example is below.

The new scheduler tries to address this by making do_rm_work tasks the
one with the highest priority and running them even when the maximum
number of running tasks has been reached.

In addition, debug output is always produced which helps debug priotities further.

$ bitbake core-image-minimal
[...]
NOTE: recipe qemu-native-2.4.0.1-r1: task do_populate_sysroot: Started
NOTE: recipe qemu-native-2.4.0.1-r1: task do_populate_sysroot: Succeeded
NOTE: Running noexec task 1373 of 2269 (ID: 145, virtual:native:.../qemu_2.4.0.1.bb, do_build)
NOTE: Running task 1374 of 2269 (ID: 146, virtual:native:.../qemu_2.4.0.1.bb, do_rm_work)
NOTE: recipe qemu-native-2.4.0.1-r1: task do_rm_work: Started
NOTE: recipe qemu-native-2.4.0.1-r1: task do_rm_work: Succeeded
...
NOTE: recipe gmp-6.0.0-r0: task do_packagedata: Succeeded
NOTE: Running task 1456 of 2269 (ID: 2168, .../gmp_6.0.0.bb, do_package_write_ipk)
NOTE: recipe gmp-6.0.0-r0: task do_package_write_ipk: Started
NOTE: recipe gmp-6.0.0-r0: task do_package_write_ipk: Succeeded

[... nothing more for gmp; instead, several other tasks run ...]

NOTE: Running task 1493 of 2269 (ID: 1801, .../libcheck_0.10.0.bb, do_fetch)
ERROR: No new tasks can be executed since the disk space monitor action is "STOPTASKS"!
WARNING: The free space of .../downloads (rootfs) is running low (0.487GB left)
ERROR: No new tasks can be executed since the disk space monitor action is "STOPTASKS"!
[...]
$ (du -h -c -s $(ls -1 -d downloads/* downloads/git2/* | grep -v -e '.done$' -e '/git2$')) || true
752K	downloads/check-0.10.0.tar.gz
1.6M	downloads/git2/github.com.Samsung.cynara.git
53M	downloads/git2/github.com.systemd.systemd.git
973M	downloads/git2/git.yoctoproject.org.linux-yocto-4.1.git
2.1M	downloads/git2/git.yoctoproject.org.prelink-cross.git
22M	downloads/git2/git.yoctoproject.org.yocto-kernel-cache
192K	downloads/git2/review.tizen.org.platform.core.appfw.tizen-platform-wrapper
1.3M	downloads/git2/review.tizen.org.platform.upstream.smack
272M	downloads/git2/sourceware.org.git.binutils-gdb.git
0	downloads/git2/sourceware.org.git.binutils-gdb.git.lock
2.3M	downloads/gmp-6.0.0a.tar.bz2
1.3G	total

Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>